# Generated by Django 2.1.5 on 2019-01-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190121_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(error_messages={'required': 'gender field is required'}, max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(error_messages={'required': 'phone field is required'}, max_length=20),
        ),
    ]
