# Generated by Django 2.1.5 on 2019-02-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190128_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(error_messages={'required': 'gender field is required'}, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(error_messages={'required': 'phone field is required'}, max_length=20, null=True),
        ),
    ]
