# Generated by Django 2.1.5 on 2019-01-28 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('background_image', models.ImageField(upload_to='')),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('experts', models.TextField(blank=True, max_length=500, null=True)),
                ('remember', models.TextField(blank=True, max_length=500, null=True)),
                ('extra', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('background_image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('experts', models.TextField(blank=True, max_length=500, null=True)),
                ('remember', models.TextField(blank=True, max_length=500, null=True)),
                ('extra', models.TextField(blank=True, max_length=500, null=True)),
                ('activities', models.ManyToManyField(to='mainApp.Activity')),
                ('gallery', models.ManyToManyField(to='mainApp.Gallery')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.Location')),
            ],
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='spots',
            field=models.ManyToManyField(to='mainApp.Spot'),
        ),
        migrations.AddField(
            model_name='activity',
            name='gallery',
            field=models.ManyToManyField(to='mainApp.Gallery'),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.Location'),
        ),
    ]
