# Generated by Django 2.1.5 on 2019-02-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
