# Generated by Django 2.1.5 on 2019-02-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Spot'),
        ),
    ]
