# Generated by Django 2.1.5 on 2019-02-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_userschedule_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='is_spot',
            field=models.BooleanField(default=False),
        ),
    ]
