# Generated by Django 2.1.5 on 2019-02-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20190211_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Adventure', 'Adventure')], default='Adventure', max_length=30),
        ),
    ]
