# Generated by Django 2.1.5 on 2019-02-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_auto_20190214_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Cultural', 'Cultural')], default='Adventure', max_length=30),
        ),
    ]
