# Generated by Django 2.1.5 on 2019-02-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20190215_0605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerlsPerUsd',
            new_name='PerlsPerQAR',
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Adventure', 'Adventure')], default='Adventure', max_length=30),
        ),
    ]
