# Generated by Django 2.1.5 on 2019-03-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_auto_20190215_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
