# Generated by Django 2.1.5 on 2019-03-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_booking_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Adventure', 'Adventure')], default='Adventure', max_length=30),
        ),
    ]
