# Generated by Django 2.1.5 on 2019-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20190306_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Cultural', 'Cultural')], default='Adventure', max_length=30),
        ),
        migrations.AddField(
            model_name='activity',
            name='schedules',
            field=models.ManyToManyField(to='mainApp.Schedule'),
        ),
    ]
