# Generated by Django 2.1.5 on 2019-03-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_booking_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='schedules',
        ),
        migrations.AddField(
            model_name='schedule',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Cultural', 'Cultural'), ('Adventure', 'Adventure')], default='Adventure', max_length=30),
        ),
    ]
