# Generated by Django 2.1.5 on 2019-03-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_auto_20190312_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('activity', 'id')},
        ),
    ]
